### Create booking (driver)
POST http://localhost:3000/bookings
Authorization: Bearer eyJhbGciOiJIUzI1NiIsImtpZCI6IjhJTXNuelZZYXYrLzUyNGoiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL3FoampnYnVuaGptd2xvZHdjbHB1LnN1cGFiYXNlLmNvL2F1dGgvdjEiLCJzdWIiOiJiOGZkNzgzZS03OWEzLTRhNWMtOWRlYS1mOTk3MDVkN2Q0MWIiLCJhdWQiOiJhdXRoZW50aWNhdGVkIiwiZXhwIjoxNzY1OTg5NDgyLCJpYXQiOjE3NjU5ODU4ODIsImVtYWlsIjoiZHJpdmVyQHRlc3QuY29tIiwicGhvbmUiOiIiLCJhcHBfbWV0YWRhdGEiOnsicHJvdmlkZXIiOiJlbWFpbCIsInByb3ZpZGVycyI6WyJlbWFpbCJdfSwidXNlcl9tZXRhZGF0YSI6eyJlbWFpbF92ZXJpZmllZCI6dHJ1ZX0sInJvbGUiOiJhdXRoZW50aWNhdGVkIiwiYWFsIjoiYWFsMSIsImFtciI6W3sibWV0aG9kIjoicGFzc3dvcmQiLCJ0aW1lc3RhbXAiOjE3NjU5ODU4ODJ9XSwic2Vzc2lvbl9pZCI6ImIwZmNlMDA4LTc5NmMtNDQxYi1iNDUxLTZiN2I1MWM4MTgxMyIsImlzX2Fub255bW91cyI6ZmFsc2V9.PlDT5cr1gYb-St_JQvDipztbequWR5k-T8jUSbM9hL4

Content-Type: application/json

{
  "vehicle_id": "3a1be2b1-41fe-499a-86d0-302a5b2b9ee5"
  "start_date": "2025-01-10",
  "end_date": "2025-01-20"
}
