### Get all vehicles
GET http://127.0.0.1:3000/vehicles
Authorization: Bearer eyJhbGciOiJIUzI1NiIsImtpZCI6IjhJTXNuelZZYXYrLzUyNGoiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL3FoampnYnVuaGptd2xvZHdjbHB1LnN1cGFiYXNlLmNvL2F1dGgvdjEiLCJzdWIiOiIwMDI0ZGVhNi1iOTM5LTQzOTItYTZlMi1kY2UxMmNjNDgzZGEiLCJhdWQiOiJhdXRoZW50aWNhdGVkIiwiZXhwIjoxNzY1Njc2NjA4LCJpYXQiOjE3NjU2NzMwMDgsImVtYWlsIjoiaG9zdEB0ZXN0LmNvbSIsInBob25lIjoiIiwiYXBwX21ldGFkYXRhIjp7InByb3ZpZGVyIjoiZW1haWwiLCJwcm92aWRlcnMiOlsiZW1haWwiXX0sInVzZXJfbWV0YWRhdGEiOnsiZW1haWxfdmVyaWZpZWQiOnRydWV9LCJyb2xlIjoiYXV0aGVudGljYXRlZCIsImFhbCI6ImFhbDEiLCJhbXIiOlt7Im1ldGhvZCI6InBhc3N3b3JkIiwidGltZXN0YW1wIjoxNzY1NjczMDA4fV0sInNlc3Npb25faWQiOiI2YzFkYTQxMy0yN2M2LTQ3NzktODZlOS0zODI5MzViYWYyMDQiLCJpc19hbm9ueW1vdXMiOmZhbHNlfQ.LjsecFporWPsPdBflLmTlxEAruMi0GCqgbWue4TI4Xo

### Add a test vehicle
POST http://127.0.0.1:3000/vehicles
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsImtpZCI6IjhJTXNuelZZYXYrLzUyNGoiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL3FoampnYnVuaGptd2xvZHdjbHB1LnN1cGFiYXNlLmNvL2F1dGgvdjEiLCJzdWIiOiIwMDI0ZGVhNi1iOTM5LTQzOTItYTZlMi1kY2UxMmNjNDgzZGEiLCJhdWQiOiJhdXRoZW50aWNhdGVkIiwiZXhwIjoxNzY1Njc2NjA4LCJpYXQiOjE3NjU2NzMwMDgsImVtYWlsIjoiaG9zdEB0ZXN0LmNvbSIsInBob25lIjoiIiwiYXBwX21ldGFkYXRhIjp7InByb3ZpZGVyIjoiZW1haWwiLCJwcm92aWRlcnMiOlsiZW1haWwiXX0sInVzZXJfbWV0YWRhdGEiOnsiZW1haWxfdmVyaWZpZWQiOnRydWV9LCJyb2xlIjoiYXV0aGVudGljYXRlZCIsImFhbCI6ImFhbDEiLCJhbXIiOlt7Im1ldGhvZCI6InBhc3N3b3JkIiwidGltZXN0YW1wIjoxNzY1NjczMDA4fV0sInNlc3Npb25faWQiOiI2YzFkYTQxMy0yN2M2LTQ3NzktODZlOS0zODI5MzViYWYyMDQiLCJpc19hbm9ueW1vdXMiOmZhbHNlfQ.LjsecFporWPsPdBflLmTlxEAruMi0GCqgbWue4TI4Xo

{
  "make": "Toyota",
  "model": "Corolla",
  "year": 2022,
  "price_per_day": 65,
  "image_url": "https://example.com/corolla.jpg"
}
3a1be2b1-41fe-499a-86d0-302a5b2b9ee5
### Create a booking (driver)
POST http://localhost:3000/bookings
Authorization: Bearer eyJhbGciOiJIUzI1NiIsImtpZCI6IjhJTXNuelZZYXYrLzUyNGoiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL3FoampnYnVuaGptd2xvZHdjbHB1LnN1cGFiYXNlLmNvL2F1dGgvdjEiLCJzdWIiOiJiOGZkNzgzZS03OWEzLTRhNWMtOWRlYS1mOTk3MDVkN2Q0MWIiLCJhdWQiOiJhdXRoZW50aWNhdGVkIiwiZXhwIjoxNzY1OTkxODI0LCJpYXQiOjE3NjU5ODgyMjQsImVtYWlsIjoiZHJpdmVyQHRlc3QuY29tIiwicGhvbmUiOiIiLCJhcHBfbWV0YWRhdGEiOnsicHJvdmlkZXIiOiJlbWFpbCIsInByb3ZpZGVycyI6WyJlbWFpbCJdfSwidXNlcl9tZXRhZGF0YSI6eyJlbWFpbF92ZXJpZmllZCI6dHJ1ZX0sInJvbGUiOiJhdXRoZW50aWNhdGVkIiwiYWFsIjoiYWFsMSIsImFtciI6W3sibWV0aG9kIjoicGFzc3dvcmQiLCJ0aW1lc3RhbXAiOjE3NjU5ODgyMjR9XSwic2Vzc2lvbl9pZCI6IjdiZGVkMzhiLWQ1MWMtNGZkZS1iYTRlLWQ1ZTIzMDkyOWExOSIsImlzX2Fub255bW91cyI6ZmFsc2V9.CETksa-dMWf272oHdK2z4W9pJtESWXM6Is_4D_xMTEs
Content-Type: application/json

{
  "vehicle_id": "3a1be2b1-41fe-499a-86d0-302a5b2b9ee5"
 ,
  "start_date": "2025-01-10",
  "end_date": "2025-01-20"
}
### Create booking (driver)
POST http://localhost:3000/bookings
Authorization: Bearer PASTE_DRIVER_ACCESS_TOKEN_HERE
Content-Type: application/json

{
  "vehicle_id": "3a1be2b1-41fe-499a-86d0-302a5b2b9ee5"
,
  "start_date": "2025-01-10",
  "end_date": "2025-01-20"
}
### Create booking (driver)
POST http://localhost:3000/bookings
Authorization: Bearer eyJhbGciOiJIUzI1NiIsImtpZCI6IjhJTXNuelZZYXYrLzUyNGoiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL3FoampnYnVuaGptd2xvZHdjbHB1LnN1cGFiYXNlLmNvL2F1dGgvdjEiLCJzdWIiOiJiOGZkNzgzZS03OWEzLTRhNWMtOWRlYS1mOTk3MDVkN2Q0MWIiLCJhdWQiOiJhdXRoZW50aWNhdGVkIiwiZXhwIjoxNzY1OTI0OTUwLCJpYXQiOjE3NjU5MjEzNTAsImVtYWlsIjoiZHJpdmVyQHRlc3QuY29tIiwicGhvbmUiOiIiLCJhcHBfbWV0YWRhdGEiOnsicHJvdmlkZXIiOiJlbWFpbCIsInByb3ZpZGVycyI6WyJlbWFpbCJdfSwidXNlcl9tZXRhZGF0YSI6eyJlbWFpbF92ZXJpZmllZCI6dHJ1ZX0sInJvbGUiOiJhdXRoZW50aWNhdGVkIiwiYWFsIjoiYWFsMSIsImFtciI6W3sibWV0aG9kIjoicGFzc3dvcmQiLCJ0aW1lc3RhbXAiOjE3NjU5MjEzNTB9XSwic2Vzc2lvbl9pZCI6IjI5Mjc2MmJjLTFkMzMtNDZiYS04NWNlLTgwYzQ3NjdkZDgzNSIsImlzX2Fub255bW91cyI6ZmFsc2V9.4yexYQwXRNyl7DvbIc9vIJ_v6WP_1vV4EaqGeo3jQuw


Content-Type: application/json

{
  "vehicle_id": "PASTE_VEHICLE_ID_HERE",
  "start_date": "2025-01-10",
  "end_date": "2025-01-20"
}
 
